#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Copy-Recursive
version:      0.13
version_from: Recursive.pm
installdirs:  site
requires:
    File::Spec:                    0
    File::Copy:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
